import Navbar from './Components/Navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html data-theme="dark" lang="fr">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
